## Lec 5
* Building a nn Using NN MODULE

In [1]:
import torch
import torch.nn as nn

In [7]:
class Model(nn.Module):
    def __init__(self,num_features):

        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward (self , features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return  out

In [8]:
# creating dataset
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.4049],
        [0.5451],
        [0.4949],
        [0.5172],
        [0.4652],
        [0.4758],
        [0.5540],
        [0.5153],
        [0.4902],
        [0.4464]], grad_fn=<SigmoidBackward0>)

In [10]:
model.linear.weight
model.linear.bias

Parameter containing:
tensor([0.3923], requires_grad=True)

In [11]:
!pip install torchinfo


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
from torchinfo import  summary
summary (model , input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [14]:
class model0 (nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()

        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()


    def forward (self,features):
        out = self.linear1(features)
        out= self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out


In [16]:
features = torch.rand(10,5)
model2 = model0(features.shape[1])
model2(features)

tensor([[0.4583],
        [0.4801],
        [0.4539],
        [0.4721],
        [0.4603],
        [0.4490],
        [0.4613],
        [0.4851],
        [0.4373],
        [0.4660]], grad_fn=<SigmoidBackward0>)

In [17]:
model2.linear1.weight

Parameter containing:
tensor([[ 0.3616, -0.3172, -0.2688,  0.3069, -0.3461],
        [ 0.4187, -0.1892,  0.1704, -0.3387, -0.2609],
        [ 0.3625,  0.4387, -0.0365,  0.2755, -0.4438]], requires_grad=True)

In [19]:
summary(model2,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model0                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## making sequential container


In [20]:
class model4 (nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(nn.Linear(num_features,3),
                                     nn.ReLU(),
                                     nn.Linear(3,1),
                                     nn.Sigmoid()
                                     )

    def forward (self,features):
        out = self.network(features)
        return out


In [21]:
mod = model4(features.shape[1])
mod(features)

tensor([[0.4399],
        [0.4273],
        [0.4379],
        [0.4218],
        [0.4391],
        [0.4401],
        [0.4319],
        [0.4265],
        [0.4402],
        [0.4369]], grad_fn=<SigmoidBackward0>)

In [23]:
summary(mod,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model4                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00